---
# tasks file for apigee-opdk-yum-packages

- name: Update basic yum os packages with no proxy
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ yum_os_minimum_packages }}"
  when: yum_os_minimum_packages is defined
